# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/toshiba/betelgeuse/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
 vendor/toshiba/betelgeuse/proprietary/bin/nvcap_test:system/bin/nvcap_test \
 vendor/toshiba/betelgeuse/proprietary/bin/nvdmmultidisplay:system/bin/nvdmmultidisplay \
 vendor/toshiba/betelgeuse/proprietary/bin/tegrastats:system/bin/tegrastats \
 vendor/toshiba/betelgeuse/proprietary/bin/nv_hciattach:system/bin/nv_hciattach \
 vendor/toshiba/betelgeuse/proprietary/bin/nvtest:system/bin/nvtest \
 vendor/toshiba/betelgeuse/proprietary/bin/nvcpud:system/bin/nvcpud \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvodm_hdmi.so:system/lib/libnvodm_hdmi.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvmm_service.so:system/lib/libnvmm_service.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvrm_graphics.so:system/lib/libnvrm_graphics.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvmm_asfparser.so:system/lib/libnvmm_asfparser.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvaviparserhal.so:system/lib/libnvaviparserhal.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvomxadaptor.so:system/lib/libnvomxadaptor.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvmmlite_image.so:system/lib/libnvmmlite_image.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvmmlite_utils.so:system/lib/libnvmmlite_utils.so \
 vendor/toshiba/betelgeuse/proprietary/lib/omxplayer.so:system/lib/omxplayer.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvcpud.so:system/lib/libnvcpud.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvos.so:system/lib/libnvos.so \
 vendor/toshiba/betelgeuse/proprietary/lib/egl/libGLESv2_tegra.so:system/lib/egl/libGLESv2_tegra.so \
 vendor/toshiba/betelgeuse/proprietary/lib/egl/libGLESv1_CM_tegra.so:system/lib/egl/libGLESv1_CM_tegra.so \
 vendor/toshiba/betelgeuse/proprietary/lib/egl/libEGL_tegra.so:system/lib/egl/libEGL_tegra.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvhdmi3dplay_jni.so:system/lib/libnvhdmi3dplay_jni.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvddk_2d_v2.so:system/lib/libnvddk_2d_v2.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libcgdrv.so:system/lib/libcgdrv.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvmm_utils.so:system/lib/libnvmm_utils.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvmm_video.so:system/lib/libnvmm_video.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvtestio.so:system/lib/libnvtestio.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvmmlite.so:system/lib/libnvmmlite.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvomxilclient.so:system/lib/libnvomxilclient.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvddk_2d.so:system/lib/libnvddk_2d.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvmm_writer.so:system/lib/libnvmm_writer.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvmm_audio.so:system/lib/libnvmm_audio.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvrm.so:system/lib/libnvrm.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvomx.so:system/lib/libnvomx.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvodm_misc.so:system/lib/libnvodm_misc.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvdispmgr_d.so:system/lib/libnvdispmgr_d.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvcap.so:system/lib/libnvcap.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvmm_misc.so:system/lib/libnvmm_misc.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvodm_dtvtuner.so:system/lib/libnvodm_dtvtuner.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvmm_parser.so:system/lib/libnvmm_parser.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvtvmr.so:system/lib/libnvtvmr.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libardrv_dynamic.so:system/lib/libardrv_dynamic.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvavp.so:system/lib/libnvavp.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvmm_vc1_video.so:system/lib/libnvmm_vc1_video.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvmm_contentpipe.so:system/lib/libnvmm_contentpipe.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvcontrol_jni.so:system/lib/libnvcontrol_jni.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvwinsys.so:system/lib/libnvwinsys.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvmmlite_audio.so:system/lib/libnvmmlite_audio.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvasfparserhal.so:system/lib/libnvasfparserhal.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvtestresults.so:system/lib/libnvtestresults.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvodm_query.so:system/lib/libnvodm_query.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvapputil.so:system/lib/libnvapputil.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvmmlite_video.so:system/lib/libnvmmlite_video.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvparser.so:system/lib/libnvparser.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvsystemuiext_jni.so:system/lib/libnvsystemuiext_jni.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvmm_manager.so:system/lib/libnvmm_manager.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvodm_imager.so:system/lib/libnvodm_imager.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvmm.so:system/lib/libnvmm.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvmm_camera.so:system/lib/libnvmm_camera.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvmm_aviparser.so:system/lib/libnvmm_aviparser.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvstereoutils_jni.so:system/lib/libnvstereoutils_jni.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvmmlite_msaudio.so:system/lib/libnvmmlite_msaudio.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvsm.so:system/lib/libnvsm.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvmm_image.so:system/lib/libnvmm_image.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvcpud_client.so:system/lib/libnvcpud_client.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvcapclk.so:system/lib/libnvcapclk.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvwsi.so:system/lib/libnvwsi.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvcap_video.so:system/lib/libnvcap_video.so \
 vendor/toshiba/betelgeuse/proprietary/lib/libnvmm_msaudio.so:system/lib/libnvmm_msaudio.so \
 vendor/toshiba/betelgeuse/proprietary/lib/hw/gralloc.tegra.so:system/lib/hw/gralloc.tegra.so \
 vendor/toshiba/betelgeuse/proprietary/lib/hw/hwcomposer.tegra.so:system/lib/hw/hwcomposer.tegra.so \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvavp_vid_ucode_alt.bin:system/etc/firmware/nvavp_vid_ucode_alt.bin \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvmm_jpegenc.axf:system/etc/firmware/nvmm_jpegenc.axf \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvmm_mpeg2dec.axf:system/etc/firmware/nvmm_mpeg2dec.axf \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvavp_os_00001000.bin:system/etc/firmware/nvavp_os_00001000.bin \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvmm_mpeg4dec.axf:system/etc/firmware/nvmm_mpeg4dec.axf \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvmm_h264dec2x.axf:system/etc/firmware/nvmm_h264dec2x.axf \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvrm_avp_eff00000.bin:system/etc/firmware/nvrm_avp_eff00000.bin \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvmm_wmaprodec.axf:system/etc/firmware/nvmm_wmaprodec.axf \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/arb_test.axf:system/etc/firmware/arb_test.axf \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/load_test2.axf:system/etc/firmware/load_test2.axf \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvmm_wmadec.axf:system/etc/firmware/nvmm_wmadec.axf \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvmm_vc1dec_2x.axf:system/etc/firmware/nvmm_vc1dec_2x.axf \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvrm_avp_0ff00000.bin:system/etc/firmware/nvrm_avp_0ff00000.bin \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/load_test0.axf:system/etc/firmware/load_test0.axf \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvavp_os_eff00000.bin:system/etc/firmware/nvavp_os_eff00000.bin \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvavp_os_0ff00000.bin:system/etc/firmware/nvavp_os_0ff00000.bin \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvmm_aacdec.axf:system/etc/firmware/nvmm_aacdec.axf \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvrm_avp_be000000.bin:system/etc/firmware/nvrm_avp_be000000.bin \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvmm_mp3dec.axf:system/etc/firmware/nvmm_mp3dec.axf \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvrm_avp_9e000000.bin:system/etc/firmware/nvrm_avp_9e000000.bin \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/load_test4.axf:system/etc/firmware/load_test4.axf \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvavp_vid_ucode.bin:system/etc/firmware/nvavp_vid_ucode.bin \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvmm_service.axf:system/etc/firmware/nvmm_service.axf \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvrm_avp.bin:system/etc/firmware/nvrm_avp.bin \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvmm_jpegdec.axf:system/etc/firmware/nvmm_jpegdec.axf \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvmm_manager.axf:system/etc/firmware/nvmm_manager.axf \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/memory_stress.axf:system/etc/firmware/memory_stress.axf \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvrm_avp_8e000000.bin:system/etc/firmware/nvrm_avp_8e000000.bin \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvavp_os_e0000000.bin:system/etc/firmware/nvavp_os_e0000000.bin \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvmm_adtsdec.axf:system/etc/firmware/nvmm_adtsdec.axf \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvmm_h264dec.axf:system/etc/firmware/nvmm_h264dec.axf \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/load_test1.axf:system/etc/firmware/load_test1.axf \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvmm_vc1dec.axf:system/etc/firmware/nvmm_vc1dec.axf \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvmm_wavdec.axf:system/etc/firmware/nvmm_wavdec.axf \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/nvmm_reference.axf:system/etc/firmware/nvmm_reference.axf \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/transport_stress.axf:system/etc/firmware/transport_stress.axf \
 vendor/toshiba/betelgeuse/proprietary/etc/firmware/load_test3.axf:system/etc/firmware/load_test3.axf
